# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-26 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoVerificationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edx_id', models.TextField()),
                ('expected_name', models.TextField()),
                ('photoid', models.TextField()),
                ('photoid_key', models.TextField()),
                ('userphoto', models.TextField()),
                ('userphoto_key', models.TextField()),
                ('response_to', models.TextField()),
                ('verified', models.IntegerField(choices=[(0, 'Undefined'), (1, 'Verified'), (2, 'Invalid')], default=0)),
            ],
        ),
    ]
