# Generated by Django 2.2.4 on 2019-08-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoverificationrequest',
            name='invalid_message',
            field=models.TextField(default=''),
        ),
    ]
