name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Build Docker image
        run: docker build . --file ./Dockerfile --tag ghcr.io/eol-uchile/edx_photo_verification:${GITHUB_SHA}

      - name: Test image
        run: docker run --rm ghcr.io/eol-uchile/edx_photo_verification:${GITHUB_SHA} python manage.py test

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: eolito
          password: ${{ secrets.CR_PAT }}

      - name: Push
        run: docker push ghcr.io/eol-uchile/edx_photo_verification:${GITHUB_SHA}
